-- MySQL Script generated by MySQL Workbench
-- Fri Apr  1 10:32:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vilela-bike
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vilela-bike
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vilela-bike` DEFAULT CHARACTER SET utf8 ;
USE `vilela-bike` ;

-- -----------------------------------------------------
-- Table `vilela-bike`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vilela-bike`.`tb_usuario` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(8) NULL,
  `senha` VARCHAR(300) NULL,
  `nome_usuario` VARCHAR(255) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vilela-bike`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vilela-bike`.`tb_cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `cpf` VARCHAR(11) NULL,
  `telefone` VARCHAR(11) NULL,
  `endereco` VARCHAR(255) NULL,
  `bairro` VARCHAR(255) NULL,
  `cidade` VARCHAR(255) NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_cliente_tb_usuario_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_tb_cliente_tb_usuario`
    FOREIGN KEY (`user_id`)
    REFERENCES `vilela-bike`.`tb_usuario` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vilela-bike`.`tb_bicicleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vilela-bike`.`tb_bicicleta` (
  `id_bicicleta` INT NOT NULL AUTO_INCREMENT,
  `aro` VARCHAR(2) NULL,
  `cor` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NULL,
  `status_bike` CHAR(1) NULL DEFAULT 0,
  PRIMARY KEY (`id_bicicleta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vilela-bike`.`tb_aluguel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vilela-bike`.`tb_aluguel` (
  `id_aluguel` INT NOT NULL AUTO_INCREMENT,
  `retirada` DATETIME NULL DEFAULT current_timestamp(),
  `entrega` DATETIME NULL,
  `observacao` MEDIUMTEXT NULL,
  `tb_bicicleta_id_bicicleta` INT NOT NULL,
  `tb_cliente_id` INT NOT NULL,
  `tb_usuario_id_user` INT NOT NULL,
  PRIMARY KEY (`id_aluguel`),
  INDEX `fk_tb_aluguel_tb_bicicleta1_idx` (`tb_bicicleta_id_bicicleta` ASC) ,
  INDEX `fk_tb_aluguel_tb_cliente1_idx` (`tb_cliente_id` ASC) ,
  INDEX `fk_tb_aluguel_tb_usuario1_idx` (`tb_usuario_id_user` ASC) ,
  CONSTRAINT `fk_tb_aluguel_tb_bicicleta1`
    FOREIGN KEY (`tb_bicicleta_id_bicicleta`)
    REFERENCES `vilela-bike`.`tb_bicicleta` (`id_bicicleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_aluguel_tb_cliente1`
    FOREIGN KEY (`tb_cliente_id`)
    REFERENCES `vilela-bike`.`tb_cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_aluguel_tb_usuario1`
    FOREIGN KEY (`tb_usuario_id_user`)
    REFERENCES `vilela-bike`.`tb_usuario` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
